import { ActiveThemeProvider } from "@/components/active-theme";
import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { cookies } from "next/headers";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const themeSettings = {
		preset: (cookieStore.get("theme_preset")?.value ?? "default") as "default",
		chartPreset: (cookieStore.get("theme_chart_preset")?.value ??
			"default") as "default",
		scale: (cookieStore.get("theme_scale")?.value ?? "none") as "none",
		radius: (cookieStore.get("theme_radius")?.value ?? "default") as "default",
		font: (cookieStore.get("theme_font")?.value ?? "default") as "default",
		contentLayout: (cookieStore.get("theme_content_layout")?.value ??
			"full") as "full",
	};

	const bodyAttributes = Object.fromEntries(
		Object.entries(themeSettings)
			.filter(([value]) => value)
			.map(([key, value]) => [
				`data-theme-${key.replace(/([A-Z])/g, "-$1").toLowerCase()}`,
				value,
			])
	);
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={cn("bg-background group/layout font-sans", fontVariables)}
				{...bodyAttributes}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					<ActiveThemeProvider initialTheme={themeSettings}>
						{children}
					</ActiveThemeProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
